# Generated by Django 5.1.6 on 2025-06-05 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0013_merge_20250427_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
